techpack: audio/asoc: fs19xx: Fix missing function prototypes
../techpack/audio/asoc/codecs/fs19xx/fsm_i2c.c:39:20: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   39 | void fsm_mutex_lock()
      |                    ^
      |                     void
../techpack/audio/asoc/codecs/fs19xx/fsm_i2c.c:44:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   44 | void fsm_mutex_unlock()
      |                      ^
      |                       void
  AR      drivers/pwm/built-in.a
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>