techpack: audio/asoc: holi: Fix missing function prototypes
../techpack/audio/asoc/holi.c:768:38: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  768 | static void msm_audio_add_qos_request()
      |                                      ^
      |                                       void
../techpack/audio/asoc/holi.c:797:41: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  797 | static void msm_audio_remove_qos_request()
      |                                         ^
      |                                          void
  AS      arch/arm64/lib/strlen.o
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>