input: touchscreen/focaltech_touch_spi: Remove dummy fw includes
Build is broken because the build system can't find these for some reason.

../drivers/input/touchscreen/focaltech_touch_spi/focaltech_flash_spi.c:62:10: fatal error: 'include/firmware/fw_sample.i' file not
found
   62 | #include FTS_UPGRADE_FW_FILE
      |          ^~~~~~~
../drivers/input/touchscreen/focaltech_touch_spi/focaltech_config.h:322:49: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
  322 | #define FTS_UPGRADE_FW_FILE                     "include/firmware/fw_sample.i"
      |                                                 ^~~~~~~~~~
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>