usb: typec: P86801_tcpc: Fix missing function prototypes
../drivers/usb/typec/P86801_tcpc/rt_pd_manager.c:260:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  260 | static int get_boot_mode(){
      |                         ^
      |                          void
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>