power: supply/wt_charger: Fix missing function prototypes
../drivers/power/supply/wt_charger/wt_chg.c:173:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  173 | static int get_boot_mode(){
      |                         ^
      |                          void

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>