techpack: camera: cam_utils: Fix missing function prototypes
../techpack/camera/drivers/cam_utils/cam_debug_util.c:22:59: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
   22 | const struct camera_debug_settings *cam_debug_get_settings()
      |                                                           ^
      |                                                            void
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>