usb: typec: P86801_tcpc: Remove unused `local_index` var
../drivers/usb/typec/P86801_tcpc/pd_dpm_alt_mode_dp.c:352:6: error: variable 'local_index' set but not used [-Werror,-Wunused-but-set-variable]
  352 |         int local_index = -1, remote_index = -1;
      |             ^
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>