power: supply/battery_secrete: ds28e30lib: Drop unused `sha1functionselect` counter
../drivers/power/supply/battery_secrete/ds28e30lib/sha256_software.c:608:11: error: variable 'sha1functionselect' set but not used [-Werror,-Wunused-but-set-variable]
  608 |    ushort sha1functionselect = 0;
      |           ^
1 error generated.

../drivers/power/supply/battery_secrete/ds28e30lib/ucl_sia256.c:417:8: error: variable 'sha1functionselect' set but not used [-Werror,-Wunused-but-set-variable]
  417 |    u32 sha1functionselect = 0;
      |        ^
1 error generated.

Seems like they stopped using this at some point and forgot to delete it.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>